# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb603c7cca17d465429e791a62fda8481975c41ff0f819ba40729c05a0159c9c283300f1fe4999da4eee2c4bc213acef93f5a8101f08484e0b230903742a06a

test:
  secret_key_base: 198f4f3fa62480b2113995df8411514cc5d76ce912676a29b1f8bd5ffc037cc4f91056224b308f7847612ac852369bb00bcefb71b99a9d931126d5a978f106d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
